package org.apache.cayenne.testdo.relationships_with_multiple_joins.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.relationships_with_multiple_joins.Invoice;

/**
 * Class _InvoiceLine was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InvoiceLine extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String INVOICE_NUMBER_PK_COLUMN = "invoice_number";
    public static final String LINE_NUMBER_PK_COLUMN = "line_number";
    public static final String YEAR_PK_COLUMN = "year";

    public static final Property<Integer> INVOICE_NUMBER = new Property<Integer>("invoiceNumber");
    public static final Property<Integer> LINE_NUMBER = new Property<Integer>("lineNumber");
    public static final Property<Integer> YEAR = new Property<Integer>("year");
    public static final Property<Invoice> INVOICE = new Property<Invoice>("invoice");

    public void setInvoiceNumber(int invoiceNumber) {
        writeProperty("invoiceNumber", invoiceNumber);
    }
    public int getInvoiceNumber() {
        Object value = readProperty("invoiceNumber");
        return (value != null) ? (Integer) value : 0;
    }

    public void setLineNumber(int lineNumber) {
        writeProperty("lineNumber", lineNumber);
    }
    public int getLineNumber() {
        Object value = readProperty("lineNumber");
        return (value != null) ? (Integer) value : 0;
    }

    public void setYear(int year) {
        writeProperty("year", year);
    }
    public int getYear() {
        Object value = readProperty("year");
        return (value != null) ? (Integer) value : 0;
    }

    public void setInvoice(Invoice invoice) {
        setToOneTarget("invoice", invoice, true);
    }

    public Invoice getInvoice() {
        return (Invoice)readProperty("invoice");
    }


}
