package org.apache.cayenne.testdo.relationships_with_multiple_joins.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.relationships_with_multiple_joins.InvoiceLine;

/**
 * Class _Invoice was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Invoice extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String INVOICE_NUMBER_PK_COLUMN = "invoice_number";
    public static final String YEAR_PK_COLUMN = "year";

    public static final Property<Integer> INVOICE_NUMBER = new Property<Integer>("invoiceNumber");
    public static final Property<Integer> YEAR = new Property<Integer>("year");
    public static final Property<List<InvoiceLine>> INVOICE_LINES = new Property<List<InvoiceLine>>("invoiceLines");

    public void setInvoiceNumber(int invoiceNumber) {
        writeProperty("invoiceNumber", invoiceNumber);
    }
    public int getInvoiceNumber() {
        Object value = readProperty("invoiceNumber");
        return (value != null) ? (Integer) value : 0;
    }

    public void setYear(int year) {
        writeProperty("year", year);
    }
    public int getYear() {
        Object value = readProperty("year");
        return (value != null) ? (Integer) value : 0;
    }

    public void addToInvoiceLines(InvoiceLine obj) {
        addToManyTarget("invoiceLines", obj, true);
    }
    public void removeFromInvoiceLines(InvoiceLine obj) {
        removeToManyTarget("invoiceLines", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InvoiceLine> getInvoiceLines() {
        return (List<InvoiceLine>)readProperty("invoiceLines");
    }


}
